---
- name: Añadir el repositorio de Helm para Harbor
  ansible.builtin.shell: |
    helm repo add harbor https://helm.goharbor.io
    helm repo update

- name: Instalar el registro privado Harbor
  ansible.builtin.shell: |
    helm upgrade --install kubernetes-harbor harbor/harbor \
      --set image.tag={{ harbor_version }} \
      --set expose.ingress.hosts.core=harbor.arriaga.eu \
      --set expose.externalURL=https://harbor.arriaga.eu \
      --set harborAdminPassword="12345Abcde" \
      --create-namespace --namespace harbor
