---
- name: Añadir el repositorio apt de Helm (formato DEB822)
  ansible.builtin.deb822_repository:
    name: helm
    types: deb
    uris: https://packages.buildkite.com/helm-linux/helm-debian/any/
    suites: any
    components: main
    architectures: "{{ ansible_facts['architecture'] | regex_replace('x86_64', 'amd64') }}"
    signed_by: https://packages.buildkite.com/helm-linux/helm-debian/gpgkey
    state: present

- name: Actualizar el índice de paquetes
  ansible.builtin.apt:
    update_cache: true

- name: Instalar Helm
  ansible.builtin.apt:
    name:
      - helm
    state: latest
