---
- name: Crear el directorio .kube
  ansible.builtin.file:
    path: /root/.kube
    state: directory

- name: Copiar el fichero .kube/config
  ansible.builtin.copy:
    src: /root/.kube/config
    dest: /root/.kube/config
    mode: "0400"

- name: Añadir el repositorio apt de HAProxy (formato DEB822)
  ansible.builtin.deb822_repository:
    name: haproxy
    types: deb
    uris: https://haproxy.debian.net
    suites: "{{ ansible_facts['distribution_release'] | lower }}-backports-{{ haproxy_version }}"
    components: main
    architectures: "{{ ansible_facts['architecture'] | regex_replace('x86_64', 'amd64') }}"
    signed_by: https://haproxy.debian.net/bernat.debian.org.gpg
    state: present

- name: Actualizar el índice de paquetes
  ansible.builtin.apt:
    update_cache: true

- name: Instalar HAProxy
  ansible.builtin.apt:
    name:
      - haproxy={{ haproxy_version }}.*
    state: latest

- name: Parar el servicio HAProxy
  ansible.builtin.service:
    name: haproxy
    state: stopped
    enabled: false

- name: Usar el comando setcap para permitir a HAProxy utilizar los puertos 80 y 443
  ansible.builtin.command: setcap cap_net_bind_service=+ep /usr/sbin/haproxy

- name: Descargar el binario de HAProxy Ingress Controller desde GitHub
  args:
    chdir: /tmp
  ansible.builtin.shell: |
    wget https://github.com/haproxytech/kubernetes-ingress/releases/download/v{{ haproxy_ingress_controller_version }}/haproxy-ingress-controller_{{ haproxy_ingress_controller_version }}_Linux_x86_64.tar.gz
    tar -xzvf haproxy-ingress-controller_{{ haproxy_ingress_controller_version }}_Linux_x86_64.tar.gz
    cp -f ./haproxy-ingress-controller /usr/local/bin/

- name: Crear el servicio HAProxy-Ingress
  ansible.builtin.copy:
    src: ./files/haproxy-ingress.service
    dest: /lib/systemd/system/haproxy-ingress.service

- name: Arrancar el servicio HAProxy-Ingress
  ansible.builtin.service:
    name: haproxy-ingress
    state: restarted
    enabled: true
