- name: Comprobar si el cluster ya está inicializado
  ansible.builtin.stat:
    path: /etc/kubernetes/admin.conf
  register: cluster_admin_conf

- name: Inicializar el cluster de Kubernetes
  ansible.builtin.command: kubeadm init --apiserver-advertise-address="{{ node_ip }}" --apiserver-cert-extra-sans="{{ node_ip }}" --node-name kube-master --pod-network-cidr=10.244.0.0/16
  when: cluster_admin_conf.stat.exists == false

- name: Crear el directorio .kube
  ansible.builtin.file:
    path: /root/.kube
    state: directory

- name: Copiar el fichero admin.conf a .kube/config
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    mode: 0400
    remote_src: yes

- name: Generar el comando join
  ansible.builtin.command: kubeadm token create --print-join-command
  register: join_command

- name: Copiar el comando join a un fichero local
  ansible.builtin.copy:
    dest: "join"
    content: "{{ join_command.stdout_lines[0] }}"
  delegate_to: localhost
