- name: Eliminar el fichero de swap de /etc/fstab
  ansible.builtin.mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Desactivar el swap
  ansible.builtin.command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Descargar la clave de firma de paquetes de Kubernetes
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/deb/Release.key
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc

- name: Añadir el repositorio apt de Kubernetes
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/deb/ /
    state: present
    filename: kubernetes

- name: Instalar los paquetes de Kubernetes
  ansible.builtin.apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: latest

- name: Configurar la dirección IP del nodo
  ansible.builtin.lineinfile:
    path: /etc/default/kubelet
    create: yes
    line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}

- name: Reiniciar el servicio kubelet
  ansible.builtin.service:
    name: kubelet
    daemon_reload: yes
    state: restarted
