grafana:
  defaultDashboardsTimezone: Europe/Madrid

  admin:
    ## Name of the secret. Can be templated.
    existingSecret: "grafana-secrets"
    userKey: admin-user
    passwordKey: admin-password

  # To make Grafana persistent (Using Statefulset)
  #
  useStatefulSet: true

  persistence:
    type: pvc
    enabled: true
    storageClassName: "rook-cephfs"
    accessModes:
      - ReadWriteMany
    size: 20Gi
    finalizers:
      - kubernetes.io/pvc-protection

  ## Configure additional grafana datasources (passed through tpl)
  ## ref: http://docs.grafana.org/administration/provisioning/#datasources
  additionalDataSources:
    - name: loki
      access: proxy
      type: loki
      url: http://logging-loki-gateway.loki.svc.cluster.local
