- name: Definir el storage class por defecto
  shell: |
    kubectl patch storageclass rook-cephfs -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'

- name: Añadir el repositorio de Portainer
  shell: |
    helm repo add portainer https://portainer.github.io/k8s/
    helm repo update

- name: Instalar Portainer
  shell: |
    helm upgrade --install --create-namespace -n portainer portainer portainer/portainer \
      --set image.tag={{ portainer_version }} \
      --set tls.force=true \
      --set service.type=ClusterIP

- name: Copiar el fichero portainer-ingress.yml
  ansible.builtin.copy:
    src: ./files/portainer-ingress.yml
    dest: /tmp/portainer-ingress.yml

- name: Crear el Ingress para Portainer en /
  command: kubectl apply -f /tmp/portainer-ingress.yml
