- name: Instalar BIRD Internet Routing Daemon
  ansible.builtin.apt:
    name:
      - bird2
    state: latest

- name: Crear el fichero de configuración de BIRD
  ansible.builtin.shell: |
    cat > /etc/bird/bird.conf <<EOF
    router id {{ node_ip }};
    log syslog all;
    EOF

- name: Crear el fichero de configuración de BIRD
  ansible.builtin.shell: |
    cat >> /etc/bird/bird.conf <<EOF
    protocol bgp {
      local {{ node_ip }} as 65000;
      neighbor {{ item }} as 65000;
      direct;
      ipv4 {
        import filter {
          if ( net ~ [ 10.244.0.0/16{26,26} ] ) then accept;
        };
        export none;
      };
    }
    EOF
  loop: "{{ ips }}"

- name: Crear el fichero de configuración de BIRD
  ansible.builtin.shell: |
    cat >> /etc/bird/bird.conf <<EOF
    protocol kernel {
      scan time 60;
      ipv4 {
        export all;
      };
    }
    protocol device {
      scan time 60;
    }
    EOF

- name: Reiniciar el servicio BIRD
  ansible.builtin.service:
    name: bird
    daemon_reload: yes
    state: restarted
    enabled: yes
