- name: Descargar la clave de firma de paquetes de Docker
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc

- name: Obtener la arquitectura del sistema
  ansible.builtin.shell: dpkg --print-architecture
  register: debian_arch

- name: Añadir el repositorio apt para la versión estable
  ansible.builtin.apt_repository:
    repo: deb [arch={{ debian_arch.stdout }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
    state: present

- name: Instalar Docker y sus dependencias
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest

- name: Arrancar el servicio Docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: Parche para que containerd arranque correctamente
  ansible.builtin.shell: |
    containerd config default | tee /etc/containerd/config.toml >/dev/null 2>&1
    sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml

- name: Reiniciar containerd
  ansible.builtin.service:
    name: containerd
    daemon_reload: yes
    state: restarted
