- name: Crear el namespace haproxy-ingress
  command: kubectl create namespace haproxy-ingress

- name: Crear el certificado autofirmado para el Ingress
  args:
    chdir: /tmp
  shell: |
    openssl req -x509 \
    -newkey rsa:2048 \
    -keyout ingress-cert.key \
    -out ingress-cert.crt \
    -days 365 \
    -nodes \
    -subj "/C=ES/ST=Araba/L=Vitoria-Gasteiz/O=Egibide/CN=kubernetes.arriaga.eu"

- name: Crear el secreto de Kubernetes con el certificado
  args:
    chdir: /tmp
  shell: |
    kubectl create secret tls cert \
    --namespace=haproxy-ingress \
    --cert="ingress-cert.crt" \
    --key="ingress-cert.key"

- name: Copiar el fichero haproxy-ingress-config.yml
  ansible.builtin.copy:
    src: /ansible/haproxy-ingress-config.yml
    dest: /tmp/haproxy-ingress-config.yml

- name: Aplicar el fichero haproxy-ingress-config.yml
  command: kubectl apply -f /tmp/haproxy-ingress-config.yml
