- name: Descargar la clave de firma de paquetes de Helm
  get_url:
    url: https://baltocdn.com/helm/signing.asc
    dest: /usr/share/keyrings/helm.asc

- name: Obtener la arquitectura del sistema
  shell: dpkg --print-architecture
  register: debian_arch

- name: Añadir el repositorio apt para la versión estable
  apt_repository:
    repo: deb [arch={{ debian_arch.stdout }} signed-by=/usr/share/keyrings/helm.asc] https://baltocdn.com/helm/stable/debian/ all main
    state: present

- name: Instalar Helm
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - helm
