- name: Eliminar el fichero de swap de /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Desactivar el swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Descargar la clave de firma de paquetes de Kubernetes
  get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /etc/apt/trusted.gpg.d/kubernetes.gpg

- name: Añadir el repositorio apt de Kubernetes
  apt_repository:
    repo: deb [signed-by=/etc/apt/trusted.gpg.d/kubernetes.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes.list

- name: Instalar los paquetes de Kubernetes
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - kubelet
      - kubeadm
      - kubectl
  register: installed

- name: Configurar la dirección IP del nodo
  lineinfile:
    path: /etc/default/kubelet
    create: yes
    line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}

- name: Reiniciar el servicio kubelet
  service:
    name: kubelet
    daemon_reload: yes
    state: restarted
