---
- name: Comprobar los hosts disponibles
  hosts: all
  gather_facts: no
  tasks:
    - command: timeout 20 sh -c 'until nc -z $0 $1; do sleep 1; done' {{ haproxy_connection_ip }} 22
      delegate_to: localhost
      register: ping_result
      ignore_errors: yes
    - group_by: key=reachable
      when: ping_result is success

- name: Configurar el gestor de cluster Portainer
  hosts: reachable
  gather_facts: yes
  become: true
  vars_files:
    - versiones.yml
  tasks:
    # Portainer
    - name: Definir el storage class por defecto
      shell: |
        kubectl patch storageclass rook-cephfs -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'

    - name: Añadir el repositorio de Portainer
      shell: |
        helm repo add portainer https://portainer.github.io/k8s/
        helm repo update

    - name: Instalar Portainer
      shell: |
        helm upgrade --install --create-namespace -n portainer portainer portainer/portainer \
          --version {{ portainer_version }} \
          --set service.type=ClusterIP

    - name: Copiar el fichero portainer-ingress.yml
      ansible.builtin.copy:
        src: /ansible/portainer-ingress.yml
        dest: /tmp/portainer-ingress.yml

    - name: Crear el Ingress para Portainer en /
      command: kubectl apply -f /tmp/portainer-ingress.yml
