---
kubernetes_version: 1.29  # https://kubernetes.io/releases/
calico_version: 3.27.0  # https://github.com/projectcalico/calico/releases
haproxy_version: 2.8  # https://www.haproxy.org
haproxy_ingress_controller_version: 1.10.11 # https://github.com/haproxytech/kubernetes-ingress/releases
dashboard_version: 2.7.0  # https://github.com/kubernetes/dashboard/releases
rook_version: 1.13.4  # https://github.com/rook/rook/releases
