apiVersion: v1
kind: Secret
metadata:
  name: harbor-secrets
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: HARBOR_ADMIN_PASSWORD
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-secrets
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: secretKey
    secret-generator.v1.mittwald.de/length: "16"
type: Opaque
