persistence:
  persistentVolumeClaim:
    registry:
      storageClass: "rook-cephfs"
      accessMode: ReadWriteMany
      size: 40Gi
    jobservice:
      jobLog:
        storageClass: "rook-cephfs"
        accessMode: ReadWriteMany
        size: 10Gi
    database:
      storageClass: "rook-cephfs"
      accessMode: ReadWriteMany
      size: 5Gi
    redis:
      storageClass: "rook-cephfs"
      accessMode: ReadWriteMany
      size: 5Gi
    trivy:
      storageClass: "rook-cephfs"
      accessMode: ReadWriteMany
      size: 40Gi
